version: '3.8'

services:
  xhs-share:
    build: .
    image: xhs-share-downloader:latest  
    container_name: xhs
    ports:
      - "10010:10010"
    environment:
      - FLASK_APP=app.py
    restart: unless-stopped
